# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5adb2c3aa099727cae801cd01f4e2166db442e10f45a43d1cbd38bf67684307a60228a1143e56d8151282c5a0a6a46e2082de9227e269e6dd3c6e441fb1e619

test:
  secret_key_base: 89e7b4c32d1962c94b5100d648688e532b4e1d84a902b36ed14f1ceb08312f3bd6657cce45f4fea7aa6472fef203dd363eca5b48dfe67051ed6edadfb6e1bca1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
